"""S&P 500 stock universe grouped by GICS sector.

Curated top-15 per sector by market cap. Refresh quarterly or when the
S&P 500 reconstitution schedule changes (typically March/June/September/December).
"""

from __future__ import annotations

SP500_BY_SECTOR: dict[str, list[dict[str, str]]] = {
    "Information Technology": [
        {"ticker": "AAPL",  "name": "Apple"},
        {"ticker": "MSFT",  "name": "Microsoft"},
        {"ticker": "NVDA",  "name": "NVIDIA"},
        {"ticker": "AVGO",  "name": "Broadcom"},
        {"ticker": "ORCL",  "name": "Oracle"},
        {"ticker": "CRM",   "name": "Salesforce"},
        {"ticker": "AMD",   "name": "AMD"},
        {"ticker": "QCOM",  "name": "Qualcomm"},
        {"ticker": "TXN",   "name": "Texas Instruments"},
        {"ticker": "INTU",  "name": "Intuit"},
        {"ticker": "NOW",   "name": "ServiceNow"},
        {"ticker": "AMAT",  "name": "Applied Materials"},
        {"ticker": "IBM",   "name": "IBM"},
        {"ticker": "KLAC",  "name": "KLA Corporation"},
        {"ticker": "INTC",  "name": "Intel"},
    ],
    "Health Care": [
        {"ticker": "UNH",  "name": "UnitedHealth"},
        {"ticker": "JNJ",  "name": "Johnson & Johnson"},
        {"ticker": "LLY",  "name": "Eli Lilly"},
        {"ticker": "ABBV", "name": "AbbVie"},
        {"ticker": "MRK",  "name": "Merck"},
        {"ticker": "TMO",  "name": "Thermo Fisher"},
        {"ticker": "ABT",  "name": "Abbott"},
        {"ticker": "DHR",  "name": "Danaher"},
        {"ticker": "ISRG", "name": "Intuitive Surgical"},
        {"ticker": "VRTX", "name": "Vertex Pharma"},
        {"ticker": "AMGN", "name": "Amgen"},
        {"ticker": "REGN", "name": "Regeneron"},
        {"ticker": "BMY",  "name": "Bristol-Myers Squibb"},
        {"ticker": "SYK",  "name": "Stryker"},
        {"ticker": "MDT",  "name": "Medtronic"},
    ],
    "Financials": [
        {"ticker": "JPM",  "name": "JPMorgan Chase"},
        {"ticker": "BAC",  "name": "Bank of America"},
        {"ticker": "WFC",  "name": "Wells Fargo"},
        {"ticker": "GS",   "name": "Goldman Sachs"},
        {"ticker": "MS",   "name": "Morgan Stanley"},
        {"ticker": "BLK",  "name": "BlackRock"},
        {"ticker": "C",    "name": "Citigroup"},
        {"ticker": "AXP",  "name": "American Express"},
        {"ticker": "SCHW", "name": "Charles Schwab"},
        {"ticker": "COF",  "name": "Capital One"},
        {"ticker": "CB",   "name": "Chubb"},
        {"ticker": "PGR",  "name": "Progressive"},
        {"ticker": "MMC",  "name": "Marsh McLennan"},
        {"ticker": "TFC",  "name": "Truist Financial"},
        {"ticker": "USB",  "name": "U.S. Bancorp"},
    ],
    "Communication Services": [
        {"ticker": "META",  "name": "Meta Platforms"},
        {"ticker": "GOOGL", "name": "Alphabet (A)"},
        {"ticker": "GOOG",  "name": "Alphabet (C)"},
        {"ticker": "NFLX",  "name": "Netflix"},
        {"ticker": "DIS",   "name": "Disney"},
        {"ticker": "CMCSA", "name": "Comcast"},
        {"ticker": "T",     "name": "AT&T"},
        {"ticker": "VZ",    "name": "Verizon"},
        {"ticker": "TMUS",  "name": "T-Mobile"},
        {"ticker": "EA",    "name": "Electronic Arts"},
        {"ticker": "TTWO",  "name": "Take-Two Interactive"},
        {"ticker": "OMC",   "name": "Omnicom"},
        {"ticker": "IPG",   "name": "Interpublic"},
        {"ticker": "WBD",   "name": "Warner Bros. Discovery"},
        {"ticker": "FOXA",  "name": "Fox Corporation"},
    ],
    "Consumer Discretionary": [
        {"ticker": "AMZN", "name": "Amazon"},
        {"ticker": "TSLA", "name": "Tesla"},
        {"ticker": "HD",   "name": "Home Depot"},
        {"ticker": "MCD",  "name": "McDonald's"},
        {"ticker": "NKE",  "name": "Nike"},
        {"ticker": "LOW",  "name": "Lowe's"},
        {"ticker": "SBUX", "name": "Starbucks"},
        {"ticker": "TGT",  "name": "Target"},
        {"ticker": "TJX",  "name": "TJX Companies"},
        {"ticker": "BKNG", "name": "Booking Holdings"},
        {"ticker": "ORLY", "name": "O'Reilly Auto"},
        {"ticker": "ABNB", "name": "Airbnb"},
        {"ticker": "MAR",  "name": "Marriott"},
        {"ticker": "GM",   "name": "General Motors"},
        {"ticker": "F",    "name": "Ford Motor"},
    ],
    "Consumer Staples": [
        {"ticker": "WMT",  "name": "Walmart"},
        {"ticker": "PG",   "name": "Procter & Gamble"},
        {"ticker": "KO",   "name": "Coca-Cola"},
        {"ticker": "PEP",  "name": "PepsiCo"},
        {"ticker": "COST", "name": "Costco"},
        {"ticker": "PM",   "name": "Philip Morris"},
        {"ticker": "MO",   "name": "Altria"},
        {"ticker": "CL",   "name": "Colgate-Palmolive"},
        {"ticker": "MDLZ", "name": "Mondelez"},
        {"ticker": "KMB",  "name": "Kimberly-Clark"},
        {"ticker": "GIS",  "name": "General Mills"},
        {"ticker": "K",    "name": "Kellanova"},
        {"ticker": "SYY",  "name": "Sysco"},
        {"ticker": "HSY",  "name": "Hershey"},
        {"ticker": "EL",   "name": "Estée Lauder"},
    ],
    "Industrials": [
        {"ticker": "GE",  "name": "GE Aerospace"},
        {"ticker": "CAT", "name": "Caterpillar"},
        {"ticker": "RTX", "name": "RTX Corporation"},
        {"ticker": "HON", "name": "Honeywell"},
        {"ticker": "UNP", "name": "Union Pacific"},
        {"ticker": "BA",  "name": "Boeing"},
        {"ticker": "UPS", "name": "UPS"},
        {"ticker": "DE",  "name": "John Deere"},
        {"ticker": "LMT", "name": "Lockheed Martin"},
        {"ticker": "MMM", "name": "3M"},
        {"ticker": "ETN", "name": "Eaton"},
        {"ticker": "EMR", "name": "Emerson Electric"},
        {"ticker": "ITW", "name": "Illinois Tool Works"},
        {"ticker": "FDX", "name": "FedEx"},
        {"ticker": "CSX", "name": "CSX"},
    ],
    "Energy": [
        {"ticker": "XOM",  "name": "ExxonMobil"},
        {"ticker": "CVX",  "name": "Chevron"},
        {"ticker": "COP",  "name": "ConocoPhillips"},
        {"ticker": "EOG",  "name": "EOG Resources"},
        {"ticker": "SLB",  "name": "Schlumberger"},
        {"ticker": "MPC",  "name": "Marathon Petroleum"},
        {"ticker": "PSX",  "name": "Phillips 66"},
        {"ticker": "VLO",  "name": "Valero Energy"},
        {"ticker": "OXY",  "name": "Occidental Petroleum"},
        {"ticker": "DVN",  "name": "Devon Energy"},
        {"ticker": "HAL",  "name": "Halliburton"},
        {"ticker": "FANG", "name": "Diamondback Energy"},
        {"ticker": "APA",  "name": "APA Corporation"},
        {"ticker": "EQT",  "name": "EQT Corporation"},
        {"ticker": "HES",  "name": "Hess"},
    ],
    "Materials": [
        {"ticker": "LIN",  "name": "Linde"},
        {"ticker": "APD",  "name": "Air Products"},
        {"ticker": "SHW",  "name": "Sherwin-Williams"},
        {"ticker": "FCX",  "name": "Freeport-McMoRan"},
        {"ticker": "NEM",  "name": "Newmont"},
        {"ticker": "NUE",  "name": "Nucor"},
        {"ticker": "VMC",  "name": "Vulcan Materials"},
        {"ticker": "MLM",  "name": "Martin Marietta"},
        {"ticker": "ALB",  "name": "Albemarle"},
        {"ticker": "CF",   "name": "CF Industries"},
        {"ticker": "MOS",  "name": "Mosaic"},
        {"ticker": "EMN",  "name": "Eastman Chemical"},
        {"ticker": "FMC",  "name": "FMC Corporation"},
        {"ticker": "IFF",  "name": "Int'l Flavors"},
        {"ticker": "PPG",  "name": "PPG Industries"},
    ],
    "Real Estate": [
        {"ticker": "AMT",  "name": "American Tower"},
        {"ticker": "PLD",  "name": "Prologis"},
        {"ticker": "EQIX", "name": "Equinix"},
        {"ticker": "CCI",  "name": "Crown Castle"},
        {"ticker": "SPG",  "name": "Simon Property"},
        {"ticker": "DLR",  "name": "Digital Realty"},
        {"ticker": "O",    "name": "Realty Income"},
        {"ticker": "WELL", "name": "Welltower"},
        {"ticker": "PSA",  "name": "Public Storage"},
        {"ticker": "EXR",  "name": "Extra Space Storage"},
        {"ticker": "AVB",  "name": "AvalonBay"},
        {"ticker": "EQR",  "name": "Equity Residential"},
        {"ticker": "VTR",  "name": "Ventas"},
        {"ticker": "ARE",  "name": "Alexandria Real Estate"},
        {"ticker": "BXP",  "name": "BXP"},
    ],
    "Utilities": [
        {"ticker": "NEE", "name": "NextEra Energy"},
        {"ticker": "SO",  "name": "Southern Company"},
        {"ticker": "DUK", "name": "Duke Energy"},
        {"ticker": "AEP", "name": "American Electric Power"},
        {"ticker": "EXC", "name": "Exelon"},
        {"ticker": "SRE", "name": "Sempra"},
        {"ticker": "D",   "name": "Dominion Energy"},
        {"ticker": "PCG", "name": "PG&E"},
        {"ticker": "XEL", "name": "Xcel Energy"},
        {"ticker": "WEC", "name": "WEC Energy"},
        {"ticker": "ETR", "name": "Entergy"},
        {"ticker": "PPL", "name": "PPL Corporation"},
        {"ticker": "FE",  "name": "FirstEnergy"},
        {"ticker": "CMS", "name": "CMS Energy"},
        {"ticker": "AES", "name": "AES Corporation"},
    ],
}


def get_sp500_by_sector() -> dict[str, list[dict[str, str]]]:
    return SP500_BY_SECTOR
